topics = [
    "ask the user for their age",
    "ask the user for their name",
    "ask the user for their email",
    "ask the user for their password",
    "ask the user for a random number",
    "ask the user for the date",
    "ask the user for the time",
    "ask the user for the year",
    "ask the user for the day of the week",
    "ask the user for the weather",
    "ask the user for their address",
    "ask the user for their phone number",
    "ask the user to select from a list of options",
    "ask the user to enter a file path",
    "ask the user to enter a URL",
    "ask the user to enter an RGB value",
    "ask the user to enter a hex value",
    "ask the user to enter their operating system",
    "ask the user for a search query",
    "ask the user for a string",
    "ask the user to play a game",
    "ask the user for their credit card number",
    "ask the user for their social security number",
    "ask the user for their bank account number",
    "ask the user for their mother's maiden name",
    "ask the user for their date of birth",
    "ask the user for their favorite color",
    "ask the user for their favorite food",
    "ask the user for their favorite movie",
    "ask the user for their country of origin",
    "ask the user for the name of their first pet",
    "ask the user for the name of their first school",
    "ask the user for the name of their first teacher",
    "ask the user whether they are a robot",
    "ask the user for their time zone",
    "ask the user for their favorite animal",
    "ask the user for the name of their hometown",
    "ask the user for their favorite book",
    "ask the user for their weight",
    "ask the user for their height",
    "ask the user for their race",
    "ask the user for their work experience",
    "ask the user for their job title",
    "ask the user for their salary",
    "ask the user for their resume",
    "ask the user for their marriage status",
    "ask the user for their favorite sport",
    "ask the user for their hobbies",
    "ask the user for their zodiac sign",
    "ask the user for their favorite music genre",
    "ask the user for their favorite travel destination",
    "ask the user for their dream job",
    "ask the user for their favorite quote",
    "ask the user for their shoe size",
    "ask the user for their favorite season",
    "ask the user for their dream vacation",
    "ask the user for their favorite superhero",
    "ask the user for their favorite video game",
    "ask the user for their favorite board game",
    "ask the user for their favorite programming language",
    "ask the user for their favorite TV show",
    "ask the user for their favorite hobby",
    "ask the user if they prefer coffee or tea",
    "ask the user about their most memorable childhood experience",
    "ask the user about their proudest achievement",
    "ask the user about their favorite childhood book",
    "ask the user about their favorite childhood game",
    "ask the user about their role model",
    "ask the user about their favorite historical figure",
    "ask the user about their most significant life lesson",
    "ask the user about their favorite type of art",
    "ask the user about their favorite form of exercise",
    "ask the user about their favorite type of cuisine",
    "ask the user about their favorite form of entertainment",
    "ask the user about their favorite ice cream flavor",
    "ask the user about their favorite fictional character",
    "ask the user about their favorite type of weather",
    "ask the user about their favorite mode of transportation",
    "ask the user about their favorite type of technology",
    "ask the user about their favorite way to relax",
    "ask the user about their favorite holiday tradition",
    "ask the user about their favorite childhood toy",
    "ask the user about their favorite type of dance",
    "ask the user about their favorite historical period",
    "ask the user about their favorite outdoor activity",
    "ask the user about their favorite indoor activity",
    "ask the user for two numbers and calculate their sum",
    "ask the user for two numbers and calculate their difference",
    "ask the user for two numbers and calculate their product",
    "ask the user for two numbers and calculate their quotient",
    "ask the user for two numbers and calculate their remainder",
    "ask the user for two numbers and calculate their average",
    "ask the user for two numbers and calculate their maximum",
    "ask the user for two numbers and calculate their minimum",
    "ask the user for a number and calculate its square",
    "ask the user for a number and calculate its square root",
    "ask the user for a number and calculate its cube",
    "ask the user for a number and calculate its factorial",
    "ask the user for a number and calculate its logarithm",
    "ask the user for a number and calculate its sine",
    "ask the user for a number and calculate its cosine",
    "ask the user for a number and calculate its tangent",
    "ask the user for two points and calculate the distance between them",
    "ask the user for the length, width, and height and calculate the volume",
    "ask the user for the coefficients of a quadratic equation and calculate its roots",
    "ask the user for the sides of a triangle and calculate its area using Heron's formula",
    "ask the user for the radius and height of a cylinder and calculate its volume",
    "ask the user for the dimensions of a rectangular prism and calculate its volume",
    "ask the user for the values of a and b in a linear equation (y = ax + b) and find the x-intercept",
    "ask the user for the radius of a circle and calculate its circumference",
    "ask the user for the coordinates of three points and check if they form a triangle",
    "ask the user for the base and height of a triangle and calculate its area",
    "ask the user for the principal amount, interest rate, and time period and calculate simple interest",
    "ask the user for the dimensions of a sphere and calculate its volume",
    "ask the user for the lengths of three sides of a triangle and check if it is a right-angled triangle",
    "ask the user for the radius of a circle and calculate its area",
    "ask the user for the coefficients of a quadratic equation and find its discriminant",
    "ask the user for the values of a, b, and c in a cubic equation and find its roots",
    "ask the user for the dimensions of a cone and calculate its volume",
    "ask the user for the lengths of three sides of a triangle and calculate its perimeter",
    "ask the user for the sides of a polygon and calculate its area using the Shoelace formula",
    "ask the user for their preferred method of communication (e.g., email, phone call, text message, etc.)",
    "ask the user for their favorite historical event or period",
    "ask the user for the number of siblings they have",
    "ask the user for their favorite type of dessert",
    "ask the user for their preferred social media platform",
    "ask the user about their favorite childhood memory with a pet",
    "ask the user for their favorite type of vehicle (e.g., car, motorcycle, bicycle, etc.)",
    "ask the user for their favorite style of architecture (e.g., Gothic, Art Deco, Modern, etc.)",
    "ask the user for their preferred method of learning (e.g., reading, watching videos, hands-on practice, etc.)",
    "present the user with a set of colors and ask them to choose their favorite",
    "present the user with a list of movies and ask them to select one for a movie night",
    "provide the user with a quiz and ask them to answer a set of questions to test their knowledge on a specific topic",
    "create a menu of cuisines and ask the user to choose what they would like to have for dinner",
    "offer the user a list of travel destinations and ask them to pick their dream vacation spot",
    "ask the user for the length of a side and calculate the area of a square",
    "ask the user for the radius of a sphere and calculate its surface area",
    "ask the user for the dimensions of a rectangular box and calculate its surface area",
    "ask the user for two angles of a triangle and calculate the third angle",
    "ask the user for the base and height of a parallelogram and calculate its area",
    "ask the user a series of general knowledge questions and keep track of their score",
    "present the user with a riddle and ask them to solve it",
    "ask the user to identify famous landmarks from images",
    "test the user's knowledge of music by asking them to guess the artist of a given song",
    "ask the user to role-play as a historical figure and answer questions as if they were that person",
    "simulate a conversation with the user as a chatbot with different personas (e.g., a helpful assistant, a playful character, etc.)",
    "create a text-based adventure game where the user makes decisions to progress through a story",
    "ask the user to write a simple program to print a pattern (e.g., a pyramid of stars) based on their input",
    "present the user with a coding problem and ask them to write a function to solve it",
    "pose a logic puzzle to the user and ask them to deduce the correct answer",
    "ask the user to calculate the factorial of a number",
    "play a number guessing game with the user",
    "ask the user to convert a temperature between Celsius and Fahrenheit",
    "ask the user to enter a list of numbers and find the largest and smallest values",
    "quiz the user on their knowledge of different programming languages",
    "ask the user to create a simple to-do list program",
    "present the user with a word jumble and challenge them to unscramble it",
    "ask the user to identify animals based on their characteristics",
    "create a rock-paper-scissors game for the user to play",
    "ask the user to solve basic math problems like addition, subtraction, multiplication, and division",
    "ask the user to perform string manipulation tasks, such as reversing a string or counting occurrences of a character",
    "present the user with a fun fact and ask them a related trivia question",
    "ask the user to write a program to check if a given number is prime",
    "simulate a virtual dice roll and ask the user to guess the number",
    "ask the user to enter their birthdate and calculate their age",
    "present the user with a list of movie quotes and ask them to name the movie",
    "ask the user to convert units, such as feet to meters or pounds to kilograms",
    "simulate a magic 8-ball and provide random answers to the user's questions",
    "ask the user to identify famous paintings or artworks from their descriptions",
    "create a hangman game where the user guesses letters to complete a hidden word",
    "ask the user to solve math word problems involving real-life scenarios",
    "ask the user about their favorite childhood cartoon or TV show",
    "ask the user to share a piece of advice they would give to their younger self",
    "ask the user to describe their morning routine",
    "ask the user for a fun fact about themselves",
    "ask the user about their favorite type of flower",
    "ask the user for their most-used smartphone app",
    "ask the user about their favorite form of physical exercise",
    "ask the user about their favorite cuisine from a different culture",
    "ask the user to name a skill or hobby they would like to learn in the future",
    "ask the user to share a unique talent they have",
    "ask the user about a recent book they read and their opinion on it",
    "ask the user for their favorite season for fashion and clothing style",
    "ask the user about their favorite memory from a family gathering",
    "ask the user about their favorite recipe and cooking experience",
    "ask the user to share an interesting historical fact or event they find fascinating",
    "ask the user for their favorite quote from a famous person and its significance to them",
    "ask the user to describe a dream they vividly remember",
    "ask the user about their favorite type of art exhibition (e.g., sculpture, photography, etc.)",
    "ask the user to share a meaningful life lesson they learned from a difficult experience",
    "ask the user about their favorite charity or cause they are passionate about",
    "ask the user for their favorite genre of podcast and recommend a popular one in that category",
]